### ISSUE TITLE
Dashboard App instance 개수 표시

### ISSUE THREAD

**Issue by jinyoung** [TheOpenCloudEngine/uEngine-cloud#53]
현재 App instance 개수가 dev + staging + prod 개수로 표시되는 문제..

실제로는 각각이 나뉘어져 표시되어야 함. 운영자가 프로덕션이 저 인스턴스 개수인 것으로 오인할 수 있음. 

ex) dev (1), prod (2)

**Comment by SeungpilPark** [comment]
현재 좌측 화살표 클릭시, 영역별로 인스턴스 개수가 표시됨.

<img width="682" alt="2018-02-01 1 50 33" src="https://user-images.githubusercontent.com/13447690/35661646-eaeea840-0756-11e8-86a4-b69ef07e88f8.png">

화살표 클릭을 하지 않아도 알 수 있도록 dev (1), prod (2) 으로 표기가 필요
